apiVersion: v1
kind: Secret
metadata:
 name: spring-secret
type: Opaque

stringData:
 SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/login_db
 SPRING_DATASOURCE_USERNAME: vittal777
 SPRING_DATASOURCE_PASSWORD: "696969"